### ISSUE TITLE
Guard Villagers (Forge&Fabric both) can't step on 1 block height after killing any mob. Bug appears only with Mob AI Tweaks

### ISSUE THREAD

**Issue by Didygan** [Unknowneth/Mob-AI-Tweaks#16]
https://imgur.com/a/ohd3Jh8

**Comment by Unknowneth** [comment]
Fixed as of 1.5.0

**Comment by Libvion** [comment]
Bug still happens on the fabric version of 1.5.0 to 1.6.0 in version 1.20.1
